import Head from 'next/head'
import { Navbar } from 'layouts';


export default function Home() {
  return (
    <div  >
      <Head>
        <title>Traderly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      </Head>


      <Navbar />
      <main  >
        <h1>Vincent</h1>
      </main>

    </div>
  )
}
